In [2]:
# import library
import numpy as np

In [3]:
# creating the 1-D Array
one_D_Array = np.array([1,2,3,4,5])

In [4]:
one_D_Array

array([1, 2, 3, 4, 5])

In [5]:
print(type(one_D_Array))

<class 'numpy.ndarray'>


In [6]:
# another way to create an array by using the np.arrange() method
one_D_arr = np.arange(4) # it return the evenly spaced array.

In [7]:
one_D_arr

array([0, 1, 2, 3])

In [11]:
np.arange(0,100,5) # 3rd paramater show the distance between number of an array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [13]:
# the above array is used to generate the arrays in integer format if it is in the decimal one then we use linespace() method for it
decimal_values = np.linspace(0,100,20) # paramater 1-start 2-end value 3-numbers exists in array.

In [17]:
print(decimal_values)
print(f"len of array is : {len(decimal_values)}") # we can also the dtypes of these number using paramater as dtype="int" in linespace method.

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
len of array is : 20


In [18]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML!']
<U23


<!-- # More on NumPy arrays¶
# One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:

# np.ones() - Returns a new array setting values to one.
# np.zeros() - Returns a new array setting values to zero.
# np.empty() - Returns a new uninitialized array.
# np.random.rand() - Returns a new array with values chosen at random. -->

# More on NumPy arrays¶
One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:

- "np.ones()" - Returns a new array setting values to one.
- "np.zeros()" - Returns a new array setting values to zero.
- "np.empty()" - Returns a new uninitialized array.
- "np.random.rand()" - Returns a new array with values chosen at random.

In [19]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
np.empty(3)

array([0., 0., 0.])

In [31]:
np.random.rand(3,3) # first paramater shows as row and 2nd show as column

array([[0.28875009, 0.38164207, 0.94533008],
       [0.59302342, 0.14200763, 0.22215607],
       [0.70439033, 0.35136212, 0.28229408]])

# Multidimensional Arrays¶
With NumPy you can also create arrays with more than one dimension. In the above examples, you dealt with 1-D arrays, where you can access their elements using a single index.
A multidimensional array has more than one column. Think of a multidimensional array as an excel sheet where each row/column represents a dimension.

![0_Vh-pKXTJsdL-9FT0.png](attachment:0_Vh-pKXTJsdL-9FT0.png)

In [33]:
# one way to create the multi-dimensional array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# 2nd way
SD_array = np.array([1,2,3,4,5,6])

In [44]:
# then single array will reshape as multi-dimensional..
np.reshape(SD_array,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                    SD_array, # the array to be reshaped
                    (2,3) # dimensions of the new array
                )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


# Finding size, shape and dimension
In future assignments, you will need to know how to find the size, dimension and shape of an array. These are all atrributes of a ndarray and can be accessed as follows:
## ndarray.ndim =Stores the number dimensions of the array
## ndarray.shape = Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
## ndarray.size = Stores the number of elements in the array

In [49]:
print(f"shape is : {SD_array.shape}")
print(f"size is : {S_array.size}")
print(f"dimension is : {S_array.ndim}")

shape is : (6,)
size is : 6
dimension is : 1


# Array math operations
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list. Meanwhile, trying to subtract or multipy Python lists simply would cause an error.

In [50]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


# Multiplying vector with a scalar (broadcasting)
Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

This concept is called broadcasting, which allows you to perform operations specifically on arrays of different shapes.

In [51]:
vector = np.array([1, 2, 3, 4, 5, 6])
vector * 1.6

array([1.6, 3.2, 4.8, 6.4, 8. , 9.6])

# Indexing and slicing
- Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays.

- Indexing
. Let us select specific elements from the arrays as given.

In [52]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [53]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j and two sets of brackets
print(two_dim[2][1])

# Select element number 8 from the 2-D array, this time using i and j indexes in a single 
# set of brackets, separated by a comma
print(two_dim[2,1])

8
8


# Slicing
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive).

The syntax is:

array[start:end:step]

If no value is passed to start, it is assumed start = 0, if no value is passed to end, it is assumed that end = length of array - 1 and if no value is passed to step, it is assumed step = 1.

Note you can use slice notation with multi-dimensional indexing, as in a[0:2, :5]. This is the extent of indexing you'll need for this course but feel free to check out the official NumPy documentation for extensive documentation on more advanced NumPy array indexing techniques.

In [54]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [55]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [56]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [ ]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

In [ ]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

In [59]:
SD_array[:]

array([1, 2, 3, 4, 5, 6])

In [62]:
SD_array[::3]

array([1, 4])

In [63]:
SD_array[:4]

array([1, 2, 3, 4])

In [64]:
# This example uses slice notation to get every row, and then pulls the second column.
# Notice how this example combines slice notation with the use of multiple indexes
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


# Stacking
Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis

- np.vstack() - stacks vertically
- 
np.hstack() - stacks horizontall
- np.hsplit() - splits an array into several smaller arrays

In [65]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [66]:
# stack the array vertically
V_array = np.vstack((a1,a2)) # it works on 2-D array in tuple

In [67]:
print(V_array)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [75]:
V_split_array = np.vsplit(V_array,2) # split the array in 2 dimensions of stack array.

In [74]:
V_split_array

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]

In [76]:
# stacking array horizentally
H_stack_array = np.hstack((a1,a2))

In [77]:
H_stack_array

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [78]:
# splitting the Horizental stack array into specific dimension
H_Split_array =  np.hsplit(H_stack_array,2)

In [79]:
H_Split_array

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]